version: '3.8'

services:
  image-service:
    image: image-service:latest
    ports:
      - "8080:8080"
    volumes:
      - image-service:/api/v1/
    depends_on:
      - mysql-db
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysql-db:3306/image-service",
            "spring.datasource.username" : "$MYSQL_USER",
            "spring.datasource.password" : "$MYSQL_PASSWORD",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.main.allow-circular-references": "true",
            "upload.path": "api/v1/images"
          }'
  mysql-db:
    image: mysql:8.0
    ports:
      - "30306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: image-service
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  image-service:
